config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    resources :attendances, only: [:index, :new, :create]
  end
  resources :users, only: [:show, :update, :edit]

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end



  #get 'events/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :send_participation_email

  validates :stripe_customer_id, presence: true

  belongs_to :user
  belongs_to :event

  private

  def send_participation_email
    ParticipationMailer.participation_email(event.user, user).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  validates :start_date, presence: true
  validates :duration, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :location, presence: true

  has_many :attendances
  has_many :participants, through: :attendances, source: :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances
  has_many :events

  has_one_attached :avatar

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event

    def index
        id = params[:event_id]
        @event = Event.find(id)
    end


  def new
    @attendance = Attendance.new
    # Assurez-vous que l'utilisateur n'est pas déjà participant ou administrateur de l'événement
    if current_user == @event.user || @event.participants.include?(current_user)
      flash[:error] = "Vous êtes déjà inscrit à cet événement."
      redirect_to @event
    end
  end

  def create
    @attendance = Attendance.new(attendance_params)
    @attendance.user = current_user
    @attendance.event = @event

    if @attendance.save
      flash[:success] = "Inscription réussie à l'événement !"
      redirect_to @event
    else
      flash[:error] = "Une erreur est survenue lors de l'inscription à l'événement."
      render :new
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def attendance_params
    params.require(:attendance).permit(:stripe_customer_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event = current_user.events.build(event_params)
    @event.save
    if @event.save
      flash[:success] = "évènement créé avec succès !"
      redirect_to root_path
    else
      flash.now[:error] = "Une ou plusieurs erreurs ont été détectées : #{@event.errors.full_messages.join(" , ")}"
      redirect_to new_event_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:user_id, :start_date, :duration, :title, :description, :price, :location)
  end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :update]

  attr_accessor :first_name, :last_name, :description, :email, :password, :password_confirmation, :current_password

  def show
    # Assure que seul l'utilisateur concerné peut accéder à sa page de profil
    unless current_user == @user
      redirect_to root_path, alert: "Accès non autorisé."
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)

    if @user.update(user_params)
      flash[:success] = "Vos informations ont été mises à jour avec succès !"
      redirect_to user_path(current_user)
    else
      flash[:error] = "Erreur lors de la mise à jour de vos données. Veuillez vérifier les informations."
      redirect_to user_path(current_user)
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/index.html.erb
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Participants de l'événement</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <main>
    <div class="container mt-5">
      <div class="card">
        <div class="card-header bg-dark text-white">
          <h5 class="card-title">Participants de l'événement</h5>
        </div>
        <div class="card-body">
          <% if flash[:error] %>
            <div class="alert alert-danger" role="alert">
              <%= flash[:error] %>
            </div>
          <% elsif flash[:success] %>
            <div class="alert alert-success" role="alert">
              <%= flash[:success] %>
            </div>
          <% end %>
          <div class="price">
            <p> Il y a  <%= @event.participants.count %> participants à cet évènement :  </p>
          </div>
          <% if @event.participants.any? %>
            <% @event.participants.each do |participant| %>
              <p class="color_font"><%= participant.first_name %> <%= participant.last_name %></p>
            <% end %>
          <% else %>
            <p>Il n'y a pas de participant pour le moment.</p>
          <% end %>
          <div class="card-body">
          <%= link_to "Retour", event_path(@event.id), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
</html>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil - Mon Site</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <% if flash[:success].present? %>
    <div class="alert alert-success" role="alert">
    <%= flash[:success] %>
    </div>
    <% end %>


    <div class="container mt-5">
    <div class="jumbotron text-center">
        <h1 class="display-4">Bienvenue sur EventbriteTest !</h1>
        <p class="lead">Trouve et partage des événements passionnants.</p>
        <a class="btn btn-primary btn-lg" href="/events/new" role="button">Créer un événement</a>
    </div>

    <div class="text-center">
        <img src="<%= asset_path('beyonce') %>" class="img-fluid rounded-start" alt="Beyoncé">
    </div>
    </div>

<h2 class="mb-4">Événements à venir :</h2>
<div class="row">
    <!-- Boucle pour afficher chaque événement -->
    <% @events.each do |event| %>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <img src="<%= asset_path('event_image') %>" class="card-img-top" alt="<%= event.title %>">
                <div class="card-body">
                    <h5 class="card-title"><%= event.title %></h5>
                    <p class="card-text"><%= event.description %></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <%= link_to "Voir", event_path(event), class: "btn btn-sm btn-outline-secondary" %>
                        </div>
                        <small class="text-muted"><%= event.start_date.strftime("%d %B %Y") %></small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    <!-- Fin de la boucle pour afficher chaque événement -->
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

app/views/events/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title">Créer un nouvel événement</h1>

          <%= form_with(model: @event, url: events_path) do |form| %>
            <%= form.hidden_field :user_id, value: current_user.id %> <!-- Champ caché pour user_id -->

            <div class="form-group">
              <%= form.label :start_date, class: "form-label" %>
              <%= form.datetime_local_field :start_date, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :duration, class: "form-label" %>
              <%= form.number_field :duration, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :title, class: "form-label" %>
              <%= form.text_field :title, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_area :description, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :price, class: "form-label" %>
              <%= form.number_field :price, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :location, class: "form-label" %>
              <%= form.text_field :location, class: "form-control" %>
            </div>

            <div class="actions">
              <%= form.submit "Créer l'événement", class: "btn btn-primary" %>
            </div>
          <% end %>

          <%= link_to "Retour", events_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @event.title %></h5>
      <p class="card-text"><%= @event.description %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Date de début : <%= @event.start_date.strftime("%d %B %Y") %></li>
      <li class="list-group-item">Durée : <%= @event.duration %> heures</li>
      <li class="list-group-item">Prix : <%= @event.price %> €</li>
      <li class="list-group-item">Lieu : <%= @event.location %></li>
    </ul>
    <div class="card-body">
      <%= link_to "Retour", events_path, class: "btn btn-primary" %>
    </div>
    <div class="card-body">
      <% if user_signed_in? %>
        <div class="btn-group" role="group">
          <div class="mr-2">
          <a href="/events/<%=@event.id%>/attendances" class="btn btn-primary">Voir les participants</a>
          </div>
          <% if !@event.participants.include?(current_user) %>
            <%= form_tag('/attendances', id: 'payment-form') do %>
              <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-amount="<%= (@event.price * 100).to_i %>"
                data-name="Mon application"
                data-description="Paiement pour <%= @event.title %> "
                data-locale="auto">
              </script>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- jQuery (nécessaire pour les plugins JavaScript de Bootstrap) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+z8vwuK7/iphhFFPIbcS+6Bf8EETO1SzI2KR0pP" crossorigin="anonymous"></script>

<!-- Popper.js (nécessaire pour les plugins JavaScript de Bootstrap) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js" integrity="sha384-N3fwbv0U/U4xMdAdO8eWtKtZlMbsWJHgqNbUuWjhav2j7rW2tLg4f+hEKq1Rfwwb" crossorigin="anonymous"></script>

<!-- JavaScript de Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-dZk+tgM/X6LBzQ3eHikxuJr6EWEnwYrH+5Xr6AoPL5NUtE+BsRG+JXmUuAxSN2ol" crossorigin="anonymous"></script>

<!-- JavaScript de Stripe -->
<script src="https://js.stripe.com/v3/"></script>

<!-- JavaScript de Font Awesome -->
<script src="https://kit.fontawesome.com/622df1b05f.js" crossorigin="anonymous"></script>

  <title>EvenbriteTest</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="">EventbriteTest</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/events">Accueil/Liste des Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/events/new">Créer un événement</a>
                </li>
                </ul>
            </div>
            <%if user_signed_in?%>
           
              <li class="nav-item">
                 <%= link_to "Mon profil", user_path(current_user), class: "nav-link", style: "color: #adb5bd;" %>
              </li>
              <li class="nav-item">
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link", style: "color: #adb5bd;", data: {turbo_method: :delete} %>
              </li>

            <%else%>
            <!-- Ajoute le lien vers la page d'inscription ici -->
            <li class="nav-item">
              <%= link_to "S'inscrire", new_user_registration_path , class: "nav-link", style: "color: #adb5bd;" %>
            </li>
            <li class="nav-item">
             <%= link_to "Se connecter", new_user_session_path , class: "nav-link", style: "color: #adb5bd;" %>
            </li>
            <%end%>
            </div>
        </nav>
    </header>
    <%= yield %>
     <% flash.each do |key, value| %>
    <div class="alert alert-<%= key == :notice ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

     <footer class="footer bg-dark text-white mt-5">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-12">
                    <!-- Ajoutez vos liens de médias sociaux ici -->
                    <a href="#"><i class="fab fa-facebook-f fa-lg text-white mx-3"></i></a>
                    <a href="#"><i class="fab fa-instagram fa-lg text-white mx-3"></i></a>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <p>&copy; 2024 EventbriteTest. Tous droits réservés.</p>
                </div>
            </div>
        </div>
    </footer>
  </body>


</html>

app/views/users/show.html.erb
<div class="container d-flex justify-content-center">
  <div class="card mx-auto" style="width: 18rem;">
    <% if @user.avatar.attached? %>
      <%= image_tag url_for(@user.avatar), class: "card-img-top", alt: "Photo de profil" %>
    <% else %>
      <div class="card-img-top">
        <p>Aucune photo de profil pour le moment.</p>
      </div>
    <% end %>
    <div class="card-body">
      <h5 class="card-title">Profil de <%= @user.first_name %> <%= @user.last_name %></h5>
      <p class="card-text">Description : <%= @user.description %></p>
      <p class="card-text">Email : <%= @user.email %></p>

      <h5 class="card-title">Événements créés par <%= @user.first_name %></h5>
      <% @user.events.each do |event| %>
        <p class="card-text"><%= link_to event.title, event_path(event) %></p>
      <% end %>

      <% if current_user == @user %>
        <%= link_to "Modifier mon profil", edit_user_registration_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>